SET FOREIGN_KEY_CHECKS = 0;
drop table if EXISTS Customer, Orders;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Customer(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(200) NOT NULL,
    password VARCHAR(128) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Orders(
    id INT AUTO_INCREMENT PRIMARY KEY,
    customerId int NOT NULL,
    paymentStatus Boolean NOT NULL,
    paymentType ENUM('CREDIT_CARD', 'DEBIT_CARD', 'UPI', 'CASH') NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customerId) REFERENCES Customer(id)
);
