CREATE TABLE CourseTeachers (
    id  INT PRIMARY KEY AUTO_INCREMENT,
    course_id INT NOT NULL,
    teacher_id INT NOT NULL,
    Createdby bigint not null,
    Createdon DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (teacher_id) REFERENCES Teacher(id) ON DELETE CASCADE ON UPDATE CASCADE
);
