CREATE TABLE Enrollment (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    student_id INT NOT NULL,
    course_id INT not null,
    enrollment_date DATE NOT NULL,
    Createdon DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES Student(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE ON UPDATE CASCADE
);
